export default {
  id: "gapgpt",
  priority: 96,
  alias: "gg",
  uiAlias: "gg",
  display: {
    name: "GapGPT",
    icon: "code",
    color: "#00B8A9",
    website: "https://gapgpt.app",
    notice: {
      signupUrl: "https://gapgpt.app/gapcode",
    },
  },
  category: "oauth",
  // OAuth only: GapGPT/GapCode never exposes a raw API key in its panel — the CLI
  // "OAuth" flow is the sole way to obtain the credential (it returns an api_key,
  // which we store as the bearer token). So no manual API-key entry in the UI.
  authModes: ["oauth"],
  hasOAuth: true,
  thinkingConfig: {
    options: [
      "auto",
      "none",
      "low",
      "medium",
      "high",
    ],
    defaultMode: "auto",
  },
  // GapCode is a fork of the OpenAI Codex CLI: it speaks the Responses API
  // (instructions/input/reasoning, store=false, forced streaming) against
  // api.gapgpt.app/v1/responses and serves the Codex model family. Handled by
  // the shared CodexExecutor (registered under "gapgpt" in executors/index.js).
  transport: {
    baseUrl: "https://api.gapgpt.app/v1/responses",
    format: "openai-responses",
    forceStream: true,
    headers: {
      originator: "codex_cli_rs",
    },
    usage: {
      url: "https://gapgpt.app/api/v1/api/codex/usage",
    },
  },
  models: [
    { id: "gpt-6-astra", name: "GPT-6 Astra" },
    { id: "gpt-6.1-sol", name: "GPT-6.1 Sol" },
    { id: "gpt-6-luna", name: "GPT-6 Luna" },
    { id: "gpt-6-sol", name: "GPT-6 Sol" },
    { id: "kimi-3", name: "Kimi 3" },
    { id: "glm-5.3", name: "GLM-5.3" },
    { id: "glm-5.3-flash", name: "GLM-5.3 Flash" },
    { id: "glm-5.2", name: "GLM-5.2" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-v4.1-flash", name: "DeepSeek V4.1 Flash" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-v4-flash-vision-exp", name: "DeepSeek V4 Flash Vision Exp" },
    { id: "grok-4.6", name: "Grok 4.6" },
    { id: "claude-fable-5", name: "Claude Fable 5" },
    { id: "claude-fable-5-1", name: "Claude Fable 5.1" },
    { id: "claude-opus-5", name: "Claude Opus 5" },
    { id: "claude-opus-5-5", name: "Claude Opus 5.5" },
    { id: "claude-opus-4-8", name: "Claude Opus 4.8" },
    { id: "claude-opus-4-7", name: "Claude Opus 4.7" },
    { id: "claude-opus-4-6", name: "Claude Opus 4.6" },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5" },
    { id: "claude-sonnet-5-5", name: "Claude Sonnet 5.5" },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6" },
    { id: "claude-sonnet-4-5", name: "Claude Sonnet 4.5" },
    { id: "claude-sonnet-4-5-20250929", name: "Claude Sonnet 4.5 (20250929)" },
    { id: "claude-haiku-4-5-20251001", name: "Claude Haiku 4.5 (20251001)" },
    { id: "gapgpt-qwen-3.6", name: "GapGPT Qwen 3.6" },
    { id: "gapgpt-qwen-3.6-thinking", name: "GapGPT Qwen 3.6 Thinking" },
    { id: "gapgpt-qwen-3.5-thinking", name: "GapGPT Qwen 3.5 Thinking" },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra" },
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna" },
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol" },
    { id: "gpt-5.5", name: "GPT-5.5" },
    { id: "gpt-5.4", name: "GPT-5.4" },
    { id: "gpt-5.3-codex", name: "GPT-5.3 Codex" },
    { id: "gpt-5.3-codex-spark", name: "GPT-5.3 Codex Spark" },
    { id: "kimi-for-coding", name: "Kimi for Coding" },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "kimi-2.7", name: "Kimi 2.7" },
    { id: "k3", name: "K3" },
    { id: "qwen3-coder", name: "Qwen3 Coder" },
    { id: "Qwen/Qwen3.5-35B-A3B-FP8", name: "Qwen 3.5 35B A3B FP8" },
  ],
  serviceKinds: ["llm"],
  features: {
    usage: true,
  },
  oauth: {
    clientId: "app_EMoamEEZ73f0CkXaXp7hrann",
    authorizeUrl: "https://gapgpt.app/oauth/cli",
    tokenUrl: "https://gapgpt.app/api/v1/oauth/cli/token",
    scope: "openid profile email offline_access api.connectors.read api.connectors.invoke",
    codeChallengeMethod: "S256",
    fixedPort: 1455,
    callbackPath: "/auth/callback",
    extraParams: {
      id_token_add_organizations: "true",
      codex_cli_simplified_flow: "true",
      originator: "codex_cli_rs",
    },
    refresh: {
      encoding: "form",
    },
  },
};
